eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:127.0.0.1}:8761/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
